[package]
name = "eop-test-suite"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
doc = false
test = false

[dependencies]
eop = { workspace = true }

[dev-dependencies]
num-integer = "0.1.46"
num-traits = "0.2.19"
